host: ${HOST:localhost}
server:
  port: ${PORT:80}
  servlet.encoding:
    charset: UTF-8
    force: true
  shutdown: graceful

spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate:
#        generate_statistics: true
        jdbc.batch_size: 10
        jdbc.fetch_size: 40
        order_inserts: true
        order_updates: true
  datasource:
    initialization-mode: always
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/diploma_project}
    username: root
    password: root
  flyway.enabled: false
  mail:
    host: ${MAILGUN_SMTP_SERVER:smtp.gmail.com}
    port: ${MAILGUN_SMTP_PORT:587}
    username: ${MAILGUN_SMTP_LOGIN:diploma.project.d.p@gmail.com}
    password: ${MAILGUN_SMTP_PASSWORD:}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  servlet.multipart:
    max-file-size: 5MB
    max-request-size: 5MB
  batch.job.enabled: false # disable run batch jobs on startup
  task.scheduling.pool.size: 5

init:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone:
  email:
  copyright: Рухлядко Сергей
  copyrightFrom: 2020

captcha:
  length: 4
  width: 100
  height: 35
  fontPath: /static/fonts/OpenSans-Regular.ttf
  fontSize: 20
  grid: false
  expires.format: HOURS # ChronoUnit constant name
  expires: 1 # long

win.local-disk: C:/
upload.image-path: upload

#logging.level:
#  org.hibernate:
#    SQL: debug
#    type: trace
#  org.springframework.transaction: trace

#debug: true
#trace: true
