host: localhost
server:
  port: 80

spring:
  jpa:
    hibernate.ddl-auto: none
#    show-sql: true
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/diploma_project
    username: root
    password: root
#  flyway.enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: diploma.project.d.p@gmail.com
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  servlet.multipart:
    max-file-size: 5MB
    max-request-size: 5MB

init:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone:
  email:
  copyright: Рухлядко Сергей
  copyrightFrom: 2020

captcha:
  length: 8
  width: 100
  height: 35
  fontPath: /static/fonts/OpenSans-Regular.ttf
  fontSize: 20
  grid: false
  outdated: 1

upload.dir: C:/
static.resource.upload: file:///C:/upload/ #linux file:/upload

#logging.level.org.hibernate:
#    SQL: debug
#    type: trace
